# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3de473024b3635ccf4f39aaf15d0c959e7cfb21ebc352a5889de07077781287c55cabb3fde3c52c85e0ae2bca56ba5706acbbfcc5228d4075bda49e89692e07

test:
  secret_key_base: 912bfd98ca8b8fcbd5a67ac53a7e2f66605ddf99f65445a9ed32f43d944dd68ad0bad3e4ad04239fd791a565ea7287c168cc87c86e9dd1834452658ec86ae79e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
